version: v1

services:
  account-db:
    image: postgres:15.3-alpine
    container_name: accounts-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: accounts_db
    volumes:
      - ./app-source/src/accounts/accounts-db/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  ledger_db:
    image: postgres:15.3-alpine
    container_name: ledger-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ledger_db
      USE_DEMO_DATA: "True"
      LOCAL_ROUTING_NUM: "883745000"

    volumes:
      - ./app-source/src/ledger/ledger-db/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  userservice:
    build:
      context: ./app-source/src/accounts/userservice
      dockerfile: ../../../../docker/userservice/Dockerfile
    container_name: userservice
    environment:
      VERSION: "v1"
      TOKEN_EXPIRY_SECONDS: "3600"
      PRIV_KEY_PATH: /keys/jwtRS256.key
      PUB_KEY_PATH: /keys/jwtRS256.key.pub
      ACCOUNTS_DB_URI: postgresql://admin:admin@accounts-db:5432/accounts_db
      ENABLE_TRACING: "false"
    volumes:
      - ./local-secrets:/keys
    ports:
      - "8080:8080"
    depends_on:
      - account-db