apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: bank-of-anthos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: devops-banking-platform-userservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "v1"
        - name: TOKEN_EXPIRY_SECONDS
          value: "3600"
        # 1. FIXED: Set these to literal file paths instead of loading raw secrets text
        - name: PRIV_KEY_PATH
          value: "/etc/secrets/jwtRS256.key"
        - name: PUB_KEY_PATH
          value: "/etc/secrets/jwtRS256.key.pub"
        - name: ACCOUNTS_DB_URI
          valueFrom:
            secretKeyRef:
              name: userservice-db-credentials
              key: ACCOUNTS_DB_URI
        - name: ENABLE_TRACING
          value: "false"

        volumeMounts:
        - name: keys-volume
          mountPath: "/etc/secrets"
          readOnly: true
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080

        livenessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3

        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi

      volumes:
      - name: keys-volume
        secret:
          secretName: jwt-key
