apiVersion: v1
kind: Secret
metadata:
  name: accounts-db-credentials
  namespace: bank-of-anthos
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: acccounts_db
