apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-db
  namespace: bank-of-anthos

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ledger-db

  template:
    metadata:
      labels:
        app: ledger-db

    spec:
      containers:
      - name: ledger-db
        image: postgres:15.3-alpine

        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ledger-db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ledger-db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: ledger-db-credentials
              key: POSTGRES_DB

        ports:
        - containerPort: 5432

        volumeMounts:
        - name: ledger-db-storage
          mountPath: /var/lib/postgresql/data

        - name: initdb
          mountPath: /docker-entrypoint-initdb.d

        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
            - -d
            - ledger_db
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5

      volumes:
      - name: ledger-db-storage
        persistentVolumeClaim:
          claimName: ledger-db-pvc

      - name: initdb
        configMap:
          name: ledger-db-init
