apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerwriter
  namespace: bank-of-anthos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledgerwriter
  template:
    metadata:
      labels:
        app: ledgerwriter
    spec:
      containers:
      - name: ledgerwriter
        image: devops-banking-platform-ledgerwriter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: ledgerwriter-config
              key: VERSION
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ledgerwriter-config
              key: PORT
        - name: LOCAL_ROUTING_NUM
          valueFrom:
            configMapKeyRef:
              name: ledgerwriter-config
              key: LOCAL_ROUTING_NUM
        - name: BALANCES_API_ADDR
          valueFrom:
            configMapKeyRef:
              name: ledgerwriter-config
              key: BALANCES_API_ADDR
        - name: PUB_KEY_PATH
          value: "/etc/secrets/jwtRS256.key.pub"
        - name: ENABLE_TRACING
          valueFrom:
            configMapKeyRef:
              name: ledgerwriter-config
              key: ENABLE_TRACING
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: ledgerwriter-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: ledger-db-credentials
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ledger-db-credentials
              key: POSTGRES_PASSWORD

        volumeMounts:
        - name: keys-volume
          mountPath: "/etc/secrets"
          readOnly: true

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi

      volumes:
      - name: keys-volume
        secret:
          secretName: jwt-key
