apiVersion: apps/v1
kind: Deployment

metadata:
  name: contacts
  namespace: bank-of-anthos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
      - name: contacts
        image: devops-banking-platform-contacts:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: VERSION
          value: "v1"
        - name: TOKEN_EXPIRY_SECONDS
          value: "3600"
        - name: PRIV_KEY_PATH
          value: "/etc/secrets/jwtRS256.key"
        - name: PUB_KEY_PATH
          value: "/etc/secrets/jwtRS256.key.pub"
        - name: ACCOUNTS_DB_URI
          valueFrom:
            secretKeyRef:
              name: contacts-db-credentials
              key: ACCOUNTS_DB_URI
        - name: ENABLE_TRACING
          value: "false"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3

        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi

        volumeMounts:
        - name: keys-volume
          mountPath: "/etc/secrets"
          readOnly: true

      volumes:
      - name: keys-volume
        secret:
          secretName: jwt-key
